export const CLIENT_ERRORS = {
	CLIENT_ALREADY_HAS_ACTIVE_CONTRACTS:
		"Não é possível excluir um cliente com contratos ativos",
	CLIENT_CREATE_FORBIDDEN: "Você não tem permissão para criar clientes",
	CLIENT_CREATE_FAILED: "Erro ao criar cliente",
	CLIENT_DELETE_FORBIDDEN: "Apenas administradores podem excluir clientes",
	CLIENT_DELETE_FAILED: "Erro ao excluir cliente",
	CLIENT_NOT_FOUND: "Cliente não encontrado",
	CLIENT_RESTORE_FORBIDDEN: "Apenas administradores podem restaurar clientes",
	CLIENT_RESTORE_FAILED: "Erro ao restaurar cliente",
	CLIENT_TYPE_INACTIVE: "Selecione um tipo de cliente ativo",
	CLIENT_TYPE_NOT_FOUND: "Tipo de cliente não encontrado",
	CLIENT_TYPE_NOT_MUTABLE: "O tipo do cliente não pode ser alterado",
	CLIENT_UPDATE_FORBIDDEN: "Você não tem permissão para editar clientes",
	CLIENT_UPDATE_FAILED: "Erro ao atualizar cliente",
	CLIENT_DOCUMENT_REQUIRED: "Documento é obrigatório",
	CLIENT_DOCUMENT_CPF_INVALID: "CPF inválido",
	CLIENT_DOCUMENT_CNPJ_INVALID: "CNPJ inválido",
	CLIENT_DOCUMENT_DUPLICATE: "Este documento já está cadastrado",
	CLIENT_TYPE_INVALID: "Tipo de cliente inválido",
	CLIENT_GET_FAILED: "Erro ao buscar clientes",
	CLIENT_DETAIL_NOT_FOUND: "Cliente não encontrado",
	CLIENT_DETAIL_FAILED: "Erro ao buscar cliente",
	CLIENT_TYPES_GET_FAILED: "Erro ao buscar tipos de cliente",
	CLIENT_SELECTABLE_GET_FAILED: "Erro ao buscar clientes disponíveis",
} as const;
