export const CLIENT_ERRORS = {
	ALREADY_HAS_ACTIVE_CONTRACTS:
		"Não é possível excluir um cliente com contratos ativos",
	CREATE_FORBIDDEN: "Você não tem permissão para criar clientes",
	CREATE_FAILED: "Erro ao criar cliente",
	DELETE_FORBIDDEN: "Apenas administradores podem excluir clientes",
	DELETE_FAILED: "Erro ao excluir cliente",
	NOT_FOUND: "Cliente não encontrado",
	RESTORE_FORBIDDEN: "Apenas administradores podem restaurar clientes",
	RESTORE_FAILED: "Erro ao restaurar cliente",
	TYPE_INACTIVE: "Selecione um tipo de cliente ativo",
	TYPE_NOT_FOUND: "Tipo de cliente não encontrado",
	TYPE_NOT_MUTABLE: "O tipo do cliente não pode ser alterado",
	UPDATE_FORBIDDEN: "Você não tem permissão para editar clientes",
	UPDATE_FAILED: "Erro ao atualizar cliente",
	DOCUMENT_REQUIRED: "Documento é obrigatório",
	DOCUMENT_CPF_INVALID: "CPF inválido",
	DOCUMENT_CNPJ_INVALID: "CNPJ inválido",
	DOCUMENT_DUPLICATE: "Este documento já está cadastrado",
	TYPE_INVALID: "Tipo de cliente inválido",
	GET_FAILED: "Erro ao buscar clientes",
	DETAIL_FAILED: "Erro ao buscar cliente",
	TYPES_GET_FAILED: "Erro ao buscar tipos de cliente",
	SELECTABLE_GET_FAILED: "Erro ao buscar clientes disponíveis",
} as const;
